apiVersion: apps/v1
kind: Deployment
metadata:
  name: deyunhos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deyunhos
  template:
    metadata:
      labels:
        app: deyunhos
    spec:
      containers:
      - image: okteto.dev/deyunhos:latest
        name: deyunhos
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "3b58f7be-5a57-4bd7-9545-de68f0aae3d9"
        - name: Vless_Path
          value: "/3b58f7be-5a57-4bd7-9545-de68f0aae3d9-vless"
        - name: Vmess_UUID
          value: "e3d8a8de-dd50-4b99-b84b-8f4a5eda0e7c"
        - name: Vmess_Path
          value: "/e3d8a8de-dd50-4b99-b84b-8f4a5eda0e7c-vmess"
        - name: Share_Path
          value: "$Share_Path"
